import { Inter } from "next/font/google";
import "./globals.css";
import Transition from "../components/transition"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rishabh Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={`${inter.className} overflow-x-hidden`}>
        <Transition>{children}</Transition>
      </body>
    </html>
  );
}
